#1.Import Data

In [ ]:
import pandas as pd

print("Pandas imported successfully.")

Pandas imported successfully.

In [ ]:
df=pd.read_excel('Data Preprocessing.xlsx','Final Data')
print('File loaded successfully.')

File loaded successfully.

#2. Data Overview

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409869 entries, 0 to 409868
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Invoice                     409869 non-null  object
 1   StockCode                   409869 non-null  object
 2   Description                 409869 non-null  object
 3   Quantity                    409869 non-null  int64
 4   Price                       409869 non-null  float64
 5   Net Sales                   409869 non-null  float64
 6   Total Revenue per Customer  409869 non-null  float64
 7   Total Orders                409869 non-null  int64
 8   Average Order Value         409869 non-null  float64
 9   InvoiceDate                 409869 non-null  datetime64[ns]
 10  Customer ID                 409869 non-null  int64
 11  Country                     409869 non-null  object
 12  Customer Segment            409869 non-null  object
 13  Valid Invoice               400477 non-null  float64
 14  Month Name                  409869 non-null  object
 15  Month Number                409869 non-null  int64
 16  Season                      409869 non-null  object
 17  Year                        409869 non-null  int64
 18  Hour                        409869 non-null  int64
 19  Time Slot                   409869 non-null  object
 20  Transaction Type            409869 non-null  object
 21  Month-Year                  409869 non-null  object
 22  Quarter                     409869 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(7), object(10)
memory usage: 71.9+ MB

In [ ]:
df.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'Price',
 'Net Sales',
 'Total Revenue per Customer',
 'Total Orders',
 'Average Order Value',
 'InvoiceDate',
 'Customer ID',
 'Country',
 'Customer Segment',
 'Valid Invoice',
 'Month Name',
 'Month Number',
 'Season',
 'Year',
 'Hour',
 'Time Slot',
 'Transaction Type',
 'Month-Year',
 'Quarter']

In [ ]:
df.sample(10)

,Invoice,StockCode,Description,Quantity,Price,Net Sales,Total Revenue per Customer,Total Orders,Average Order Value,InvoiceDate,...,Valid Invoice,Month Name,Month Number,Season,Year,Hour,Time Slot,Transaction Type,Month-Year,Quarter
23478,492012,22112,CHOCOLATE HOT WATER BOTTLE,2,4.95,9.90,3958.50,4,989.6250,2009-12-15 11:49:00,...,492012.0,Dec,12,Winter,2009,11,Morning,Sale,Dec-2009,4
24592,492220,72800D,S/4 BLUE DINNER CANDLE SILVER FLOCK,1,2.55,2.55,829.67,6,138.2783,2009-12-15 17:45:00,...,492220.0,Dec,12,Winter,2009,17,Evening,Sale,Dec-2009,4
316689,527945,79321,CHILLI LIGHTS,4,4.95,19.80,1264.35,3,421.4500,2010-10-19 15:03:00,...,527945.0,Oct,10,Autumn,2010,15,Afternoon,Sale,Oct-2010,4
236468,519239,20728,LUNCH BAG CARS BLUE,3,1.65,4.95,442.29,2,221.1450,2010-08-15 13:42:00,...,519239.0,Aug,8,Summer,2010,13,Afternoon,Sale,Aug-2010,3
380678,534702,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.95,17.70,30.30,1,30.3000,2010-11-23 16:17:00,...,534702.0,Nov,11,Autumn,2010,16,Afternoon,Sale,Nov-2010,4
53881,496470,21000,ROSE DU SUD COSMETICS BAG,1,4.25,4.25,2747.08,8,343.3850,2010-02-01 15:23:00,...,496470.0,Feb,2,Winter,2010,15,Afternoon,Sale,Feb-2010,1
25849,492376,21730,GLASS STAR FROSTED T-LIGHT HOLDER,1,4.95,4.95,323.81,2,161.9050,2009-12-16 14:59:00,...,492376.0,Dec,12,Winter,2009,14,Afternoon,Sale,Dec-2009,4
77909,499752,84665,SQUARE CHERRY BLOSSOM CABINET,4,5.95,23.80,1079.00,2,539.5000,2010-03-02 11:53:00,...,499752.0,Mar,3,Spring,2010,11,Morning,Sale,Mar-2010,1
109406,503439,85049G,CHOCOLATE BOX RIBBONS,24,1.25,30.00,14012.87,27,518.9952,2010-04-01 10:16:00,...,503439.0,Apr,4,Spring,2010,10,Morning,Sale,Apr-2010,2
100506,502444,21564,PINK HEART SHAPE LOVE BUCKET,2,2.95,5.90,586.24,3,195.4133,2010-03-24 13:30:00,...,502444.0,Mar,3,Spring,2010,13,Afternoon,Sale,Mar-2010,1

#3. Check Non-Unique values and Statistics

In [ ]:
df.nunique()

Invoice                       23368
StockCode                      4027
Description                    4418
Quantity                        499
Price                           585
Net Sales                      3297
Total Revenue per Customer     4210
Total Orders                     64
Average Order Value            4194
InvoiceDate                   21612
Customer ID                    4289
Country                          37
Customer Segment                  4
Valid Invoice                 19141
Month Name                       12
Month Number                     12
Season                            4
Year                              2
Hour                             15
Time Slot                         4
Transaction Type                  2
Month-Year                       13
Quarter                           4
dtype: int64

In [ ]:
df.describe(include='all')

,Invoice,StockCode,Description,Quantity,Price,Net Sales,Total Revenue per Customer,Total Orders,Average Order Value,InvoiceDate,...,Valid Invoice,Month Name,Month Number,Season,Year,Hour,Time Slot,Transaction Type,Month-Year,Quarter
count,409869,409869,409869,409869.000000,409869.000000,409869.000000,409869.000000,409869.000000,409869.000000,409869,...,400477.000000,409869,409869.000000,409869,409869.000000,409869.000000,409869,409869,409869,409869.000000
unique,23368,4027,4418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12,NaN,4,NaN,NaN,4,2,13,NaN
top,500356,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Nov,NaN,Autumn,NaN,NaN,Afternoon,Sale,Nov-2010,NaN
freq,251,3197,3197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,59993,NaN,144493,NaN,NaN,268730,400477,59993,NaN
mean,NaN,NaN,NaN,12.930378,3.385017,20.517522,10953.417945,18.681767,473.997239,2010-06-30 22:07:03.557234176,...,514731.286738,NaN,7.390591,NaN,2009.924334,12.873545,NaN,NaN,NaN,2.782330
min,NaN,NaN,NaN,-9360.000000,0.000000,-8985.600000,0.000000,1.000000,0.000000,2009-12-01 07:45:00,...,489434.000000,NaN,1.000000,NaN,2009.000000,7.000000,NaN,NaN,NaN,1.000000
25%,NaN,NaN,NaN,2.000000,1.250000,4.560000,1140.110000,3.000000,242.906200,2010-03-26 11:21:00,...,502753.000000,NaN,4.000000,NaN,2010.000000,11.000000,NaN,NaN,NaN,2.000000
50%,NaN,NaN,NaN,5.000000,1.950000,11.800000,2551.810000,7.000000,346.730000,2010-07-08 16:08:00,...,515192.000000,NaN,8.000000,NaN,2010.000000,13.000000,NaN,NaN,NaN,3.000000
75%,NaN,NaN,NaN,12.000000,3.750000,19.500000,6493.140000,15.000000,524.875000,2010-10-14 12:44:00,...,527065.000000,NaN,11.000000,NaN,2010.000000,14.000000,NaN,NaN,NaN,4.000000
max,NaN,NaN,NaN,19152.000000,8985.600000,15818.400000,341776.730000,205.000000,11880.840000,2010-12-09 20:01:00,...,538171.000000,NaN,12.000000,NaN,2010.000000,21.000000,NaN,NaN,NaN,4.000000
std,NaN,NaN,NaN,102.128548,27.186469,75.616134,31523.456633,34.379558,477.846752,NaN,...,14088.330501,NaN,3.473771,NaN,0.264463,2.320152,NaN,NaN,NaN,1.143995

#4. Check Nulls & Duplicates

In [ ]:
df.isnull().mean()*100

Invoice                       0.000000
StockCode                     0.000000
Description                   0.000000
Quantity                      0.000000
Price                         0.000000
Net Sales                     0.000000
Total Revenue per Customer    0.000000
Total Orders                  0.000000
Average Order Value           0.000000
InvoiceDate                   0.000000
Customer ID                   0.000000
Country                       0.000000
Customer Segment              0.000000
Valid Invoice                 2.291464
Month Name                    0.000000
Month Number                  0.000000
Season                        0.000000
Year                          0.000000
Hour                          0.000000
Time Slot                     0.000000
Transaction Type              0.000000
Month-Year                    0.000000
Quarter                       0.000000
dtype: float64

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, Price, Net Sales, Total Revenue per Customer, Total Orders, Average Order Value, InvoiceDate, Customer ID, Country, Customer Segment, Valid Invoice, Month Name, Month Number, Season, Year, Hour, Time Slot, Transaction Type, Month-Year, Quarter]
Index: []

[0 rows x 23 columns]

#5. Time Period Analysis

In [ ]:
print("Date range:", df['InvoiceDate'].min(), "→", df['InvoiceDate'].max())

Date range: 2009-12-01 07:45:00 → 2010-12-09 20:01:00